name: build-net-aot

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    # 【核心配置】指定在容器内运行该 Job，AlmaLinux 8 100% 兼容你的 el8 系统，glibc 为 2.28
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0-alpine

    steps:

    # 2. 拉取代码
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install native dependencies
      run: |
        apk add --no-cache clang build-base zlib-dev

    # 4. 验证环境信息（可选，用于排错确认版本）
    - name: Verify Environment
      run: |
        dotnet --info

    # 5. 执行 Native AOT 编译
    - name: Publish Native AOT
      # 如果你的 .csproj 不在根目录，请在命令末尾加上你的项目路径，例如: ./src/MyApp.csproj
      run: dotnet publish -c Release -r linux-musl-x64 --self-contained true -p:PublishAot=true -o ./publish

    - name: Verify binary
      run: |
        file ./publish/t
        ldd ./publish/t || echo "Statically linked (no dynamic deps)"

    # 6. 将编译好的二进制文件上传为 GitHub Artifacts，供你下载
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app-linux-x64-el8
        # 请根据你的实际项目名调整此路径，当前默认是针对单项目的标准输出路径
        path: ./publish/